// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtWil8THvToipThWgBhIaqik60bM170sc',
    appId: '1:145084495345:web:7d0e5bd12f93f03299c050',
    messagingSenderId: '145084495345',
    projectId: 'smaplechat-5dcdc',
    authDomain: 'smaplechat-5dcdc.firebaseapp.com',
    storageBucket: 'smaplechat-5dcdc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVEsTtCZ81F-uW3o7rhrQSp1FtkLMIoaY',
    appId: '1:145084495345:android:4feb6534dc7e63e799c050',
    messagingSenderId: '145084495345',
    projectId: 'smaplechat-5dcdc',
    storageBucket: 'smaplechat-5dcdc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP6Vmmwf2XwlS42TBILW81Xohn8pZ5MFM',
    appId: '1:145084495345:ios:4c79b0f07b41516299c050',
    messagingSenderId: '145084495345',
    projectId: 'smaplechat-5dcdc',
    storageBucket: 'smaplechat-5dcdc.appspot.com',
    iosClientId: '145084495345-drmh48nqjdr6msf3urs6gmcqidmvp4fl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterrun',
  );
}
